import type { LetterData } from './types';

export const ALPHABET_DATA: LetterData[] = [
  { letter: 'A', choices: [{ word: 'Apple', emoji: '🍎' }, { word: 'Ant', emoji: '🐜' }, { word: 'Airplane', emoji: '✈️' }] },
  { letter: 'B', choices: [{ word: 'Ball', emoji: '⚽' }, { word: 'Banana', emoji: '🍌' }, { word: 'Bee', emoji: '🐝' }] },
  { letter: 'C', choices: [{ word: 'Cat', emoji: '🐱' }, { word: 'Car', emoji: '🚗' }, { word: 'Cake', emoji: '🍰' }] },
  { letter: 'D', choices: [{ word: 'Dog', emoji: '🐶' }, { word: 'Duck', emoji: '🦆' }, { word: 'Donut', emoji: '🍩' }] },
  { letter: 'E', choices: [{ word: 'Elephant', emoji: '🐘' }, { word: 'Egg', emoji: '🥚' }, { word: 'Earth', emoji: '🌍' }] },
  { letter: 'F', choices: [{ word: 'Fish', emoji: '🐠' }, { word: 'Frog', emoji: '🐸' }, { word: 'Fire', emoji: '🔥' }] },
  { letter: 'G', choices: [{ word: 'Goat', emoji: '🐐' }, { word: 'Grapes', emoji: '🍇' }, { word: 'Ghost', emoji: '👻' }] },
  { letter: 'H', choices: [{ word: 'Hat', emoji: '👒' }, { word: 'Heart', emoji: '❤️' }, { word: 'Horse', emoji: '🐴' }] },
  { letter: 'I', choices: [{ word: 'Ice Cream', emoji: '🍦' }, { word: 'Igloo', emoji: '🧊' }, { word: 'Island', emoji: '🏝️' }] },
  { letter: 'J', choices: [{ word: 'Juice', emoji: '🧃' }, { word: 'Jellyfish', emoji: '🌊' }, { word: 'Jacket', emoji: '🧥' }] },
  { letter: 'K', choices: [{ word: 'Kite', emoji: '🪁' }, { word: 'Key', emoji: '🔑' }, { word: 'Kangaroo', emoji: '🦘' }] },
  { letter: 'L', choices: [{ word: 'Lion', emoji: '🦁' }, { word: 'Lemon', emoji: '🍋' }, { word: 'Leaf', emoji: '🍃' }] },
  { letter: 'M', choices: [{ word: 'Monkey', emoji: '🐵' }, { word: 'Moon', emoji: '🌙' }, { word: 'Mouse', emoji: '🐭' }] },
  { letter: 'N', choices: [{ word: 'Nest', emoji: '🐦' }, { word: 'Nose', emoji: '👃' }, { word: 'Notebook', emoji: '📓' }] },
  { letter: 'O', choices: [{ word: 'Orange', emoji: '🍊' }, { word: 'Octopus', emoji: '🐙' }, { word: 'Owl', emoji: '🦉' }] },
  { letter: 'P', choices: [{ word: 'Pig', emoji: '🐷' }, { word: 'Pizza', emoji: '🍕' }, { word: 'Pencil', emoji: '✏️' }] },
  { letter: 'Q', choices: [{ word: 'Queen', emoji: '👑' }, { word: 'Question', emoji: '❓' }, { word: 'Quilt', emoji: '🧵' }] },
  { letter: 'R', choices: [{ word: 'Robot', emoji: '🤖' }, { word: 'Rainbow', emoji: '🌈' }, { word: 'Rocket', emoji: '🚀' }] },
  { letter: 'S', choices: [{ word: 'Sun', emoji: '☀️' }, { word: 'Star', emoji: '⭐' }, { word: 'Snake', emoji: '🐍' }] },
  { letter: 'T', choices: [{ word: 'Train', emoji: '🚂' }, { word: 'Tree', emoji: '🌳' }, { word: 'Tiger', emoji: '🐅' }] },
  { letter: 'U', choices: [{ word: 'Umbrella', emoji: '☂️' }, { word: 'Unicorn', emoji: '🦄' }, { word: 'UFO', emoji: '🛸' }] },
  { letter: 'V', choices: [{ word: 'Violin', emoji: '🎻' }, { word: 'Volcano', emoji: '🌋' }, { word: 'Vegetables', emoji: '🥕' }] },
  { letter: 'W', choices: [{ word: 'Watch', emoji: '⌚' }, { word: 'Whale', emoji: '🐳' }, { word: 'Watermelon', emoji: '🍉' }] },
  { letter: 'X', choices: [{ word: 'Xylophone', emoji: '🎼' }, { word: 'X-ray', emoji: '⚕️' }] },
  { letter: 'Y', choices: [{ word: 'Yacht', emoji: '⛵' }, { word: 'Yoyo', emoji: '🪀' }, { word: 'Yarn', emoji: '🧶' }] },
  { letter: 'Z', choices: [{ word: 'Zebra', emoji: '🦓' }, { word: 'Zipper', emoji: '🤐' }, { word: 'Zombie', emoji: '🧟' }] },
];
